### ISSUE TITLE
error: package NotificationCompat does not exist

### ISSUE THREAD

**Issue by togoenvogue** [letsdoit07/background_service#2]
Hello, 
Trying to follow along with your tutorial, I get this error : error: package NotificationCompat does not exist

Any idea on how to solve this ? 
I run Flutter version 1.9.1 on Linux, along with Dart version 2.5.0

Thank you
![DeepinScreenshot_select-area_20200131213004](https://user-images.githubusercontent.com/4346765/73575810-e3f91800-4470-11ea-8304-0ceac94e4525.png)

**Comment by togoenvogue** [comment]
Hello,
I got this working by replacing the line 
>>> import androidx.core.app.NotificationCompat;
by
>>> import android.support.v4.app.NotificationCompat;

NB: This is in the MyService.java file
Happy coding!

**Comment by letsdoit07** [comment]
Update your Android Compliation and target sdk to 28 or more. and open the android specific code in android studio's separate instance.

**Comment by togoenvogue** [comment]
Thank you my dear
